INSERT INTO FORMULARIO VALUES (TRUE, 1,'GOVERNAMENTAL');
INSERT INTO FORMULARIO VALUES (TRUE, 2,'VERNAMENTAL');
INSERT INTO FORMULARIO VALUES (TRUE, 3,'MENTAL');
INSERT INTO FORMULARIO VALUES (TRUE, 4,'GOV');