INSERT INTO FORMULARIO VALUES ( TRUE, 1, 'GOVERNAMENTAL');
INSERT INTO FORMULARIO VALUES ( TRUE, 2, 'GOVERNMENTAL');
INSERT INTO FORMULARIO VALUES ( TRUE, 3, 'GOVEAENTAL');
INSERT INTO FORMULARIO VALUES ( TRUE, 4, 'GRNAMENTAL');
INSERT INTO FORMULARIO VALUES ( TRUE, 5, 'OVERNAMENTAL');
INSERT INTO FORMULARIO VALUES ( TRUE, 6, 'GERNAMENTAL');
